### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by 905793933** [zhengjie9510/pyside-yolo#1]
May I ask what graphics card you are using to run the code? My computer gets stuck when I run the code.

**Comment by zhengjie9510** [comment]
I'm using NVIDIA GeForce RTX 4070 Ti. When running the code, my GPU memory usage is around 3GB with GPU utilization approximately 50%.

**Comment by 905793933** [comment]
Thanks！



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 2, 2024 09:30 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zhengjie9510/pyside-yolo] Graphics (Issue #1)




 
I'm using NVIDIA GeForce RTX 4070 Ti. When running the code, my GPU memory usage is around 3GB with GPU utilization approximately 50%.
